sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 112112

  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5tHP4Y15cuCARSb1QfK2
    access-key-secret: IkJz6V4dfLHGoy2kSFx406RpBwE8yK
    bucket-name: fioriro-sky-take-out

